-- ============================================================
-- SHIntranet 전체 DB 스크립트 (C##SH 계정)
-- 작성일 : 2026-05-16
-- 기준   : sh_company.sql 분석 + 전체 DAO 코드 역공학
-- 실행순서: 시퀀스 → 테이블 → FK → 뷰 → 함수 → 프로시저 → 초기 데이터
-- ※ 이미 객체가 존재하면 DROP 후 실행하거나 CREATE OR REPLACE 사용
-- ============================================================


-- ============================================================
-- 1. 시퀀스 (SEQUENCE)
-- ============================================================

-- 부서
CREATE SEQUENCE DEPT_SEQ              START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DEPT_HISTORY_SEQ      START WITH 6  INCREMENT BY 1 NOCACHE;
-- ^ DH01~DH05 초기 데이터 이미 존재 → 6부터 시작

-- 직급
CREATE SEQUENCE EMP_POSITION_SEQ      START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE POSITION_HISTORY_SEQ  START WITH 6  INCREMENT BY 1 NOCACHE;
-- ^ PH01~PH05 초기 데이터 이미 존재 → 6부터 시작

-- 직원
CREATE SEQUENCE EMP_SEQ               START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EXIT_EMP_INFO_SEQ     START WITH 1  INCREMENT BY 1 NOCACHE;

-- 출퇴근
CREATE SEQUENCE ATTEND_LOG_SEQ        START WITH 1  INCREMENT BY 1 NOCACHE;

-- 게시판
CREATE SEQUENCE BOARD_SEQ             START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOARD_DROP_LOG_SEQ    START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOARD_COMMENT_SEQ     START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMMENT_DROP_LOG_SEQ  START WITH 1  INCREMENT BY 1 NOCACHE;

-- 파일
CREATE SEQUENCE SH_FILE_SEQ           START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOARD_FILE_LOG_SEQ    START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DOC_FILE_SEQ          START WITH 1  INCREMENT BY 1 NOCACHE;

-- 업무
CREATE SEQUENCE WORK_SEQ              START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WORK_DEPT_RULE_SEQ    START WITH 1  INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WORK_TARGET_SEQ       START WITH 1  INCREMENT BY 1 NOCACHE;

-- 결재 문서
CREATE SEQUENCE DOC_SEQ               START WITH 1  INCREMENT BY 1 NOCACHE;

-- 담당자
CREATE SEQUENCE MANAGER_SEQ           START WITH 1  INCREMENT BY 1 NOCACHE;


-- ============================================================
-- 2. 테이블 DDL
-- ============================================================

-- ── 2-1. 부서 ───────────────────────────────────────────────
CREATE TABLE DEPT (
     DEPT_CD   CHAR(4)        NOT NULL
    ,DEPT_NAME NVARCHAR2(20)  NOT NULL
    ,CONSTRAINT PK_DEPT PRIMARY KEY (DEPT_CD)
);

CREATE TABLE DEPT_HISTORY (
     HISTORY_CD CHAR(4)        NOT NULL
    ,DEPT_CD    CHAR(4)        NOT NULL
    ,DEPT_NAME  NVARCHAR2(20)  NOT NULL
    ,REG_DT     DATE           DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_DEPT_HISTORY PRIMARY KEY (HISTORY_CD)
);

-- ── 2-2. 직급 ───────────────────────────────────────────────
CREATE TABLE EMP_POSITION (
     POSITION_CD   CHAR(4)        NOT NULL
    ,POSITION_NAME NVARCHAR2(20)  NOT NULL
    ,GRADE         NUMBER         NOT NULL
    ,CONSTRAINT PK_EMP_POSITION PRIMARY KEY (POSITION_CD)
);

CREATE TABLE POSITION_HISTORY (
     HISTORY_CD    CHAR(4)        NOT NULL
    ,POSITION_CD   CHAR(4)        NOT NULL
    ,POSITION_NAME NVARCHAR2(20)  NOT NULL
    ,GRADE         NUMBER         NOT NULL
    ,REG_DT        DATE           DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_POSITION_HISTORY PRIMARY KEY (HISTORY_CD)
);

-- ── 2-3. 직원 ───────────────────────────────────────────────
CREATE TABLE EMP (
     EMP_CD      CHAR(6)        NOT NULL   -- 'SW' + 4자리 (EMP_SEQ)
    ,DEPT_CD     CHAR(4)        NOT NULL
    ,POSITION_CD CHAR(4)        NOT NULL
    ,EMP_NAME    NVARCHAR2(20)  NOT NULL
    ,REG_DT      DATE           DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_EMP PRIMARY KEY (EMP_CD)
);

CREATE TABLE EMP_INFO (
     EMP_CD    CHAR(6)        NOT NULL
    ,PWD       VARCHAR2(100)  NOT NULL
    ,TEL       VARCHAR2(11)
    ,EMAIL     VARCHAR2(100)
    ,ADDR      VARCHAR2(200)
    ,HIRE_DATE DATE           DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_EMP_INFO PRIMARY KEY (EMP_CD)
);

-- 퇴사자 정보 보관 테이블 (EMP_EXIT 프로시저가 EMP_INFO → 여기로 이동)
CREATE TABLE EXIT_EMP_INFO (
     EXIT_NO   NUMBER         NOT NULL
    ,EMP_CD    CHAR(6)        NOT NULL
    ,TEL       VARCHAR2(11)
    ,HIRE_DATE DATE
    ,EMAIL     VARCHAR2(100)
    ,ADDR      VARCHAR2(200)
    ,EXIT_DATE DATE           DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_EXIT_EMP_INFO PRIMARY KEY (EXIT_NO)
);

-- ── 2-4. 출퇴근 ─────────────────────────────────────────────
CREATE TABLE ATTEND_TYPE (
     TYPE_CD   CHAR(3)       NOT NULL
    ,TYPE_NAME VARCHAR2(10)  NOT NULL
    ,CONSTRAINT PK_ATTEND_TYPE PRIMARY KEY (TYPE_CD)
);

CREATE TABLE ATTEND_LOG (
     LOG_NO  NUMBER   NOT NULL
    ,TYPE_CD CHAR(3)  NOT NULL
    ,EMP_CD  CHAR(6)  NOT NULL
    ,REG_DT  DATE     DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_ATTEND_LOG PRIMARY KEY (LOG_NO)
);

-- ── 2-5. 게시판 ─────────────────────────────────────────────
CREATE TABLE BOARD_TYPE (
     TYPE_CD   CHAR(3)       NOT NULL
    ,TYPE_NAME VARCHAR2(20)  NOT NULL
    ,CONSTRAINT PK_BOARD_TYPE PRIMARY KEY (TYPE_CD)
);

CREATE TABLE BOARD (
     BOARD_NO NUMBER        NOT NULL
    ,EMP_CD   CHAR(6)       NOT NULL
    ,TITLE    VARCHAR2(200) NOT NULL
    ,CONTENTS CLOB
    ,TYPE_CD  CHAR(3)       NOT NULL
    ,REG_DT   DATE          DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO)
);

-- 게시글 삭제 이력 (실제 DELETE 없이 이력 관리)
CREATE TABLE BOARD_DROP_LOG (
     LOG_NO   NUMBER  NOT NULL
    ,BOARD_NO NUMBER  NOT NULL
    ,EMP_CD   CHAR(6) NOT NULL
    ,DROP_DT  DATE    DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_BOARD_DROP_LOG PRIMARY KEY (LOG_NO)
);

-- 댓글
CREATE TABLE BOARD_COMMENT (
     COMMENT_NO NUMBER        NOT NULL
    ,BOARD_NO   NUMBER        NOT NULL
    ,EMP_CD     CHAR(6)       NOT NULL
    ,CONTENTS   VARCHAR2(1000)
    ,REG_DT     DATE          DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_NO)
);

-- 댓글 삭제 이력
CREATE TABLE COMMENT_DROP_LOG (
     LOG_NO     NUMBER  NOT NULL
    ,COMMENT_NO NUMBER  NOT NULL
    ,EMP_CD     CHAR(6) NOT NULL
    ,DROP_DT    DATE    DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_COMMENT_DROP_LOG PRIMARY KEY (LOG_NO)
);

-- ── 2-6. 파일 ───────────────────────────────────────────────
-- 공용 파일 마스터 (게시판·결재 문서 공통)
CREATE TABLE SH_FILE (
     FILE_NO    NUMBER         NOT NULL
    ,EMP_CD     CHAR(6)        NOT NULL
    ,ORIGIN_NAME VARCHAR2(200) NOT NULL
    ,SAVED_NAME  VARCHAR2(200) NOT NULL
    ,PATH        VARCHAR2(500) NOT NULL
    ,CONSTRAINT PK_SH_FILE PRIMARY KEY (FILE_NO)
);

-- 게시글-파일 매핑 (ISSUE_TYPE: 'C'=등록, 'D'=삭제)
CREATE TABLE BOARD_FILE_LOG (
     LOG_NO     NUMBER  NOT NULL
    ,BOARD_NO   NUMBER  NOT NULL
    ,FILE_NO    NUMBER  NOT NULL
    ,ISSUE_TYPE CHAR(1) NOT NULL  -- 'C':등록, 'D':삭제
    ,ISSUE_DATE DATE    DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_BOARD_FILE_LOG PRIMARY KEY (LOG_NO)
);

-- 결재문서-파일 매핑
CREATE TABLE DOC_FILE (
     DOC_FILE_NO NUMBER        NOT NULL
    ,DOC_CD      VARCHAR2(10)  NOT NULL
    ,FILE_NO     NUMBER        NOT NULL
    ,CONSTRAINT PK_DOC_FILE PRIMARY KEY (DOC_FILE_NO)
);

-- ── 2-7. 업무 ───────────────────────────────────────────────
CREATE TABLE WORK_TYPE (
     TYPE_CD   CHAR(3)       NOT NULL
    ,TYPE_NAME VARCHAR2(50)  NOT NULL
    ,CONSTRAINT PK_WORK_TYPE PRIMARY KEY (TYPE_CD)
);

-- 회사 업무 목록 ('WK' + 4자리)
CREATE TABLE WORK (
     WORK_CD   VARCHAR2(6)   NOT NULL
    ,TYPE_CD   CHAR(3)       NOT NULL
    ,EMP_CD    CHAR(6)       NOT NULL
    ,WORK_NAME VARCHAR2(100) NOT NULL
    ,REG_DT    DATE          DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_WORK PRIMARY KEY (WORK_CD)
);

-- 부서별 업무 규칙 (순서 포함)
CREATE TABLE WORK_DEPT_RULE (
     RULE_NO NUMBER        NOT NULL
    ,WORK_CD VARCHAR2(6)   NOT NULL
    ,DEPT_CD CHAR(4)       NOT NULL
    ,FLOW    NUMBER        NOT NULL
    ,CONSTRAINT PK_WORK_DEPT_RULE PRIMARY KEY (RULE_NO)
);

-- 업무 지시 대상자
CREATE TABLE WORK_TARGET (
     TARGET_NO NUMBER       NOT NULL
    ,DOC_CD    VARCHAR2(10) NOT NULL
    ,EMP_CD    CHAR(6)      NOT NULL
    ,CONSTRAINT PK_WORK_TARGET PRIMARY KEY (TARGET_NO)
);

-- ── 2-8. 결재 문서 ──────────────────────────────────────────
CREATE TABLE DOC_TYPE (
     TYPE_CD   CHAR(3)      NOT NULL
    ,TYPE_NAME VARCHAR2(50) NOT NULL
    ,CONSTRAINT PK_DOC_TYPE PRIMARY KEY (TYPE_CD)
);

-- 결재 문서 본체 (자기참조: PARENT_DOC_CD)
CREATE TABLE SH_DOCUMENT (
     DOC_CD        VARCHAR2(10)  NOT NULL
    ,PARENT_DOC_CD VARCHAR2(10)            -- 상위 문서 (업무지시 원문)
    ,TYPE_CD       CHAR(3)       NOT NULL
    ,WORK_CD       VARCHAR2(6)   NOT NULL
    ,EMP_CD        CHAR(6)       NOT NULL
    ,TITLE         VARCHAR2(200) NOT NULL
    ,CONTENTS      CLOB
    ,REG_DT        DATE          DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_SH_DOCUMENT PRIMARY KEY (DOC_CD)
);

-- 결재 종류 (승인/반려/전결 등)
CREATE TABLE APRV_TYPE (
     TYPE_CD   CHAR(3)      NOT NULL
    ,TYPE_NAME VARCHAR2(20) NOT NULL
    ,CONSTRAINT PK_APRV_TYPE PRIMARY KEY (TYPE_CD)
);

-- 결재 라인 (문서별 결재 순서)
CREATE TABLE APRV_LINE (
     DOC_CD  VARCHAR2(10) NOT NULL
    ,EMP_CD  CHAR(6)      NOT NULL
    ,FLOW    NUMBER       NOT NULL
    ,CONSTRAINT PK_APRV_LINE PRIMARY KEY (DOC_CD, EMP_CD)
);

-- 결재 이력 (결재자가 결재 처리한 기록)
CREATE TABLE APRV_LOG (
     LOG_NO   NUMBER        NOT NULL
    ,DOC_CD   VARCHAR2(10)  NOT NULL
    ,EMP_CD   CHAR(6)       NOT NULL
    ,TYPE_CD  CHAR(3)       NOT NULL  -- APRV_TYPE 참조
    ,COMMENTS VARCHAR2(500)
    ,REG_DT   DATE          DEFAULT SYSDATE NOT NULL
    ,CONSTRAINT PK_APRV_LOG PRIMARY KEY (LOG_NO)
);

-- ── 2-9. 업무 담당자 ────────────────────────────────────────
-- ISSUE_TYPE: 'S'=시작, 'E'=종료 (담당자 지정/해제 이력)
CREATE TABLE MANAGER (
     MANAGER_NO    NUMBER       NOT NULL
    ,WORK_CD       VARCHAR2(6)  NOT NULL
    ,MANAGER_EMP_CD CHAR(6)     NOT NULL
    ,REG_EMP_CD    CHAR(6)      NOT NULL
    ,ISSUE_TYPE    CHAR(1)      NOT NULL
    ,ISSUE_DATE    DATE         NOT NULL
    ,CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_NO)
);


-- ============================================================
-- 3. 외래키 제약조건 (FK)
-- ============================================================

-- EMP
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEPT
    FOREIGN KEY (DEPT_CD) REFERENCES DEPT (DEPT_CD);
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_POSITION
    FOREIGN KEY (POSITION_CD) REFERENCES EMP_POSITION (POSITION_CD);

-- EMP_INFO
ALTER TABLE EMP_INFO ADD CONSTRAINT FK_EMP_INFO_EMP
    FOREIGN KEY (EMP_CD) REFERENCES EMP (EMP_CD);

-- ATTEND_LOG
ALTER TABLE ATTEND_LOG ADD CONSTRAINT FK_ATTEND_LOG_TYPE
    FOREIGN KEY (TYPE_CD) REFERENCES ATTEND_TYPE (TYPE_CD);
ALTER TABLE ATTEND_LOG ADD CONSTRAINT FK_ATTEND_LOG_EMP
    FOREIGN KEY (EMP_CD) REFERENCES EMP (EMP_CD);

-- BOARD
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_TYPE
    FOREIGN KEY (TYPE_CD) REFERENCES BOARD_TYPE (TYPE_CD);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_EMP
    FOREIGN KEY (EMP_CD) REFERENCES EMP (EMP_CD);

-- BOARD_DROP_LOG
ALTER TABLE BOARD_DROP_LOG ADD CONSTRAINT FK_BOARD_DROP_LOG_BOARD
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD (BOARD_NO);

-- BOARD_COMMENT
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT FK_BOARD_COMMENT_BOARD
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD (BOARD_NO);

-- COMMENT_DROP_LOG
ALTER TABLE COMMENT_DROP_LOG ADD CONSTRAINT FK_COMMENT_DROP_LOG_COMMENT
    FOREIGN KEY (COMMENT_NO) REFERENCES BOARD_COMMENT (COMMENT_NO);

-- BOARD_FILE_LOG
ALTER TABLE BOARD_FILE_LOG ADD CONSTRAINT FK_BOARD_FILE_LOG_BOARD
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD (BOARD_NO);
ALTER TABLE BOARD_FILE_LOG ADD CONSTRAINT FK_BOARD_FILE_LOG_FILE
    FOREIGN KEY (FILE_NO) REFERENCES SH_FILE (FILE_NO);

-- DOC_FILE
ALTER TABLE DOC_FILE ADD CONSTRAINT FK_DOC_FILE_DOC
    FOREIGN KEY (DOC_CD) REFERENCES SH_DOCUMENT (DOC_CD);
ALTER TABLE DOC_FILE ADD CONSTRAINT FK_DOC_FILE_FILE
    FOREIGN KEY (FILE_NO) REFERENCES SH_FILE (FILE_NO);

-- WORK
ALTER TABLE WORK ADD CONSTRAINT FK_WORK_TYPE
    FOREIGN KEY (TYPE_CD) REFERENCES WORK_TYPE (TYPE_CD);

-- WORK_DEPT_RULE
ALTER TABLE WORK_DEPT_RULE ADD CONSTRAINT FK_WORK_DEPT_RULE_WORK
    FOREIGN KEY (WORK_CD) REFERENCES WORK (WORK_CD);
ALTER TABLE WORK_DEPT_RULE ADD CONSTRAINT FK_WORK_DEPT_RULE_DEPT
    FOREIGN KEY (DEPT_CD) REFERENCES DEPT (DEPT_CD);

-- SH_DOCUMENT
ALTER TABLE SH_DOCUMENT ADD CONSTRAINT FK_SH_DOCUMENT_TYPE
    FOREIGN KEY (TYPE_CD) REFERENCES DOC_TYPE (TYPE_CD);
ALTER TABLE SH_DOCUMENT ADD CONSTRAINT FK_SH_DOCUMENT_WORK
    FOREIGN KEY (WORK_CD) REFERENCES WORK (WORK_CD);

-- APRV_LINE
ALTER TABLE APRV_LINE ADD CONSTRAINT FK_APRV_LINE_DOC
    FOREIGN KEY (DOC_CD) REFERENCES SH_DOCUMENT (DOC_CD);

-- APRV_LOG
ALTER TABLE APRV_LOG ADD CONSTRAINT FK_APRV_LOG_DOC
    FOREIGN KEY (DOC_CD) REFERENCES SH_DOCUMENT (DOC_CD);
ALTER TABLE APRV_LOG ADD CONSTRAINT FK_APRV_LOG_TYPE
    FOREIGN KEY (TYPE_CD) REFERENCES APRV_TYPE (TYPE_CD);

-- MANAGER
ALTER TABLE MANAGER ADD CONSTRAINT FK_MANAGER_WORK
    FOREIGN KEY (WORK_CD) REFERENCES WORK (WORK_CD);

COMMIT;


-- ============================================================
-- 4. 뷰 (VIEW)
-- ============================================================

-- ── VIEW_EMPLOYEE : 재직 중인 직원 통합 뷰 ──────────────────
-- 퇴사자는 EMP_INFO 삭제 → INNER JOIN 으로 자동 제외
CREATE OR REPLACE VIEW VIEW_EMPLOYEE AS
SELECT A.EMP_CD, A.EMP_NAME, A.DEPT_CD
     , B.DEPT_NAME, A.POSITION_CD, D.POSITION_NAME
     , D.GRADE, C.TEL, C.EMAIL
     , C.ADDR, C.PWD, C.HIRE_DATE, A.REG_DT
FROM EMP A
JOIN DEPT         B ON A.DEPT_CD      = B.DEPT_CD
JOIN EMP_INFO     C ON A.EMP_CD       = C.EMP_CD
JOIN EMP_POSITION D ON A.POSITION_CD  = D.POSITION_CD;

-- ── VIEW_ATTEND_LOG : 출퇴근 기록 통합 뷰 ──────────────────
CREATE OR REPLACE VIEW VIEW_ATTEND_LOG AS
SELECT AL.LOG_NO
     , ATYPE.TYPE_CD
     , ATYPE.TYPE_NAME
     , AL.EMP_CD
     , E.EMP_NAME
     , E.DEPT_CD
     , D.DEPT_NAME
     , E.POSITION_CD
     , P.POSITION_NAME
     , TO_CHAR(AL.REG_DT, 'YYYY-MM-DD HH24:MI:SS') AS REG_DT
FROM ATTEND_LOG    AL
JOIN ATTEND_TYPE   ATYPE ON AL.TYPE_CD    = ATYPE.TYPE_CD
JOIN EMP           E     ON AL.EMP_CD     = E.EMP_CD
JOIN DEPT          D     ON E.DEPT_CD     = D.DEPT_CD
JOIN EMP_POSITION  P     ON E.POSITION_CD = P.POSITION_CD;

-- ── VIEW_WORK_SEARCH : 회사 업무 검색 뷰 ───────────────────
CREATE OR REPLACE VIEW VIEW_WORK_SEARCH AS
SELECT ROW_NUMBER() OVER(ORDER BY W.REG_DT DESC) AS ROW_NUM
     , WT.TYPE_NAME
     , W.WORK_NAME
     , TO_CHAR(W.REG_DT, 'YYYY-MM-DD') AS REG_DT
     , E.EMP_CD
     , D.DEPT_NAME
     , E.EMP_NAME
     , P.POSITION_NAME
     , W.WORK_CD
     , W.TYPE_CD
FROM WORK          W
JOIN WORK_TYPE     WT ON W.TYPE_CD    = WT.TYPE_CD
JOIN EMP           E  ON W.EMP_CD     = E.EMP_CD
JOIN DEPT          D  ON E.DEPT_CD    = D.DEPT_CD
JOIN EMP_POSITION  P  ON E.POSITION_CD = P.POSITION_CD;

-- ── VIEW_DEPT_WORK_SEARCH : 부서 업무 검색 뷰 ──────────────
CREATE OR REPLACE VIEW VIEW_DEPT_WORK_SEARCH AS
SELECT D.DEPT_NAME
     , WT.TYPE_NAME
     , W.WORK_NAME
     , WDR.FLOW
FROM WORK_DEPT_RULE WDR
JOIN WORK           W  ON WDR.WORK_CD = W.WORK_CD
JOIN WORK_TYPE      WT ON W.TYPE_CD   = WT.TYPE_CD
JOIN DEPT           D  ON WDR.DEPT_CD = D.DEPT_CD;

-- ── VIEW_WORK_TARGET : 업무 지시 가능 대상자 뷰 ─────────────
CREATE OR REPLACE VIEW VIEW_WORK_TARGET AS
SELECT E.EMP_CD
     , E.EMP_NAME
     , P.POSITION_NAME
     , E.DEPT_CD
     , P.GRADE
FROM EMP           E
JOIN EMP_POSITION  P  ON E.POSITION_CD = P.POSITION_CD
JOIN EMP_INFO      I  ON E.EMP_CD      = I.EMP_CD;  -- 재직자만

-- ── VIEW_MANAGER : 업무 담당자 통합 뷰 ─────────────────────
CREATE OR REPLACE VIEW VIEW_MANAGER AS
SELECT ROW_NUMBER() OVER(ORDER BY M.MANAGER_NO) AS ROW_NUM
     , M.MANAGER_NO
     , WT.TYPE_NAME
     , W.WORK_NAME
     , D.DEPT_CD
     , D.DEPT_NAME
     , M.MANAGER_EMP_CD
     , E1.EMP_NAME AS MANAGER_EMP_NAME
     , (SELECT MIN(ISSUE_DATE) FROM MANAGER
        WHERE WORK_CD = M.WORK_CD AND MANAGER_EMP_CD = M.MANAGER_EMP_CD) AS S_ISSUE_DATE
     , (SELECT MAX(ISSUE_DATE) FROM MANAGER
        WHERE WORK_CD = M.WORK_CD AND MANAGER_EMP_CD = M.MANAGER_EMP_CD) AS E_ISSUE_DATE
     , M.REG_EMP_CD
     , E2.EMP_NAME AS REG_EMP_NAME
     , M.WORK_CD
FROM MANAGER       M
JOIN WORK          W  ON M.WORK_CD         = W.WORK_CD
JOIN WORK_TYPE     WT ON W.TYPE_CD         = WT.TYPE_CD
JOIN EMP           E1 ON M.MANAGER_EMP_CD  = E1.EMP_CD
JOIN EMP           E2 ON M.REG_EMP_CD      = E2.EMP_CD
JOIN DEPT          D  ON E1.DEPT_CD        = D.DEPT_CD
WHERE M.ISSUE_TYPE = 'S'
  AND NOT EXISTS (
      SELECT 1 FROM MANAGER M2
      WHERE M2.WORK_CD       = M.WORK_CD
        AND M2.MANAGER_EMP_CD = M.MANAGER_EMP_CD
        AND M2.ISSUE_TYPE    = 'E'
        AND M2.ISSUE_DATE    > M.ISSUE_DATE
  );

-- ── VIEW_APRV_SUBMIT_LIST : 결재 상신 목록 뷰 ──────────────
CREATE OR REPLACE VIEW VIEW_APRV_SUBMIT_LIST AS
SELECT SD.DOC_CD
     , SD.EMP_CD
     , W.WORK_NAME
     , SD.TITLE
     , TO_CHAR(SD.REG_DT, 'YYYY-MM-DD') AS REG_DT
     , SD.TYPE_CD
     , DT.TYPE_NAME
     , (SELECT COUNT(*) FROM SH_DOCUMENT WHERE PARENT_DOC_CD = SD.DOC_CD) AS CHILD_CNT
     , CASE
           WHEN NOT EXISTS (SELECT 1 FROM APRV_LINE WHERE DOC_CD = SD.DOC_CD) THEN '결재불필요'
           WHEN NOT EXISTS (SELECT 1 FROM APRV_LOG  WHERE DOC_CD = SD.DOC_CD) THEN '결재대기'
           WHEN EXISTS (SELECT 1 FROM APRV_LOG WHERE DOC_CD = SD.DOC_CD AND TYPE_CD = '002') THEN '반려'
           WHEN (SELECT COUNT(*) FROM APRV_LINE WHERE DOC_CD = SD.DOC_CD) =
                (SELECT COUNT(*) FROM APRV_LOG  WHERE DOC_CD = SD.DOC_CD AND TYPE_CD IN ('001','003')) THEN '결재완료'
           ELSE '결재중'
       END AS STATUS
FROM SH_DOCUMENT SD
JOIN WORK         W  ON SD.WORK_CD = W.WORK_CD
JOIN DOC_TYPE     DT ON SD.TYPE_CD = DT.TYPE_CD
WHERE SD.PARENT_DOC_CD IS NOT NULL;

-- ── VIEW_APRV_RECEIVE_WAIT : 결재 대기 수신 목록 ────────────
CREATE OR REPLACE VIEW VIEW_APRV_RECEIVE_WAIT AS
SELECT SD.DOC_CD
     , SD.PARENT_DOC_CD
     , W.WORK_NAME
     , PD.TITLE
     , SD.EMP_CD
     , E.EMP_NAME
     , TO_CHAR(SD.REG_DT, 'YYYY-MM-DD HH24:MI') AS APRV_REG_DT
     , DT.TYPE_NAME
     , AL.EMP_CD AS APRV_EMP_CD
     , AE.EMP_NAME AS APRV_EMP_NAME
FROM SH_DOCUMENT SD
JOIN APRV_LINE   AL ON SD.DOC_CD   = AL.DOC_CD
JOIN EMP         AE ON AL.EMP_CD   = AE.EMP_CD
JOIN EMP         E  ON SD.EMP_CD   = E.EMP_CD
JOIN WORK        W  ON SD.WORK_CD  = W.WORK_CD
JOIN DOC_TYPE    DT ON SD.TYPE_CD  = DT.TYPE_CD
JOIN SH_DOCUMENT PD ON SD.PARENT_DOC_CD = PD.DOC_CD
WHERE NOT EXISTS (
    SELECT 1 FROM APRV_LOG
    WHERE DOC_CD = SD.DOC_CD AND EMP_CD = AL.EMP_CD
);

-- ── VIEW_APRV_RECEIVE_COMPLETE : 결재 완료 수신 목록 ────────
CREATE OR REPLACE VIEW VIEW_APRV_RECEIVE_COMPLETE AS
SELECT SD.DOC_CD
     , SD.PARENT_DOC_CD
     , W.WORK_NAME
     , PD.TITLE
     , SD.EMP_CD
     , E.EMP_NAME
     , ALOG.TYPE_CD AS APRV_TYPE_CD
     , AT2.TYPE_NAME AS APRV_TYPE_NAME
     , TO_CHAR(ALOG.REG_DT, 'YYYY-MM-DD') AS REG_DT
     , DT.TYPE_NAME AS DOC_TYPE_NAME
     , ALOG.EMP_CD AS APRV_EMP_CD
     , CASE
           WHEN ALOG.TYPE_CD = '002' THEN '반려'
           WHEN ALOG.TYPE_CD IN ('001','003') THEN '결재완료'
           ELSE '결재중'
       END AS STATUS
FROM SH_DOCUMENT SD
JOIN APRV_LOG    ALOG ON SD.DOC_CD   = ALOG.DOC_CD
JOIN APRV_TYPE   AT2  ON ALOG.TYPE_CD = AT2.TYPE_CD
JOIN EMP         E    ON SD.EMP_CD   = E.EMP_CD
JOIN WORK        W    ON SD.WORK_CD  = W.WORK_CD
JOIN DOC_TYPE    DT   ON SD.TYPE_CD  = DT.TYPE_CD
JOIN SH_DOCUMENT PD   ON SD.PARENT_DOC_CD = PD.DOC_CD;


-- ============================================================
-- 5. 함수 (FUNCTION)
-- ============================================================

-- 사원명 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_EMP_NAME(P_EMP_CD IN EMP.EMP_CD%TYPE)
RETURN VARCHAR2
IS
    V_EMP_NAME EMP.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_NAME INTO V_EMP_NAME
    FROM EMP WHERE EMP_CD = P_EMP_CD;
    RETURN V_EMP_NAME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
    WHEN OTHERS THEN RETURN NULL;
END FN_GET_EMP_NAME;
/

-- 현재 결재 순서 조회 함수
CREATE OR REPLACE FUNCTION FN_GET_APRV_CURRENT_FLOW(P_DOC_CD IN SH_DOCUMENT.DOC_CD%TYPE)
RETURN NUMBER
IS
    V_CURRENT_FLOW NUMBER;
BEGIN
    SELECT NVL(MIN(AL.FLOW), 0) INTO V_CURRENT_FLOW
    FROM APRV_LINE AL
    WHERE AL.DOC_CD = P_DOC_CD
      AND NOT EXISTS (
          SELECT 1 FROM APRV_LOG
          WHERE DOC_CD = AL.DOC_CD AND EMP_CD = AL.EMP_CD
      );
    RETURN V_CURRENT_FLOW;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END FN_GET_APRV_CURRENT_FLOW;
/


-- ============================================================
-- 6. 프로시저 (PROCEDURE)
-- ============================================================

-- ── 직원 ────────────────────────────────────────────────────

-- 1. 로그인
CREATE OR REPLACE PROCEDURE EMP_LOGIN (
     E_EMP_CD       IN  EMP_INFO.EMP_CD%TYPE
    ,E_EMP_PWD      IN  EMP_INFO.PWD%TYPE
    ,E_EMP_BUSEO_CD IN  EMP.DEPT_CD%TYPE
    ,E_EMP_RESULT   OUT VARCHAR2
    ,E_EMP_NAME     OUT EMP.EMP_NAME%TYPE
)
IS
    V_ID_MATCH NUMBER;
    V_PW_MATCH NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_ID_MATCH FROM EMP_INFO WHERE EMP_CD = E_EMP_CD;

    IF V_ID_MATCH = 0 THEN
        E_EMP_RESULT := 'ID_NOT_FOUND'; E_EMP_NAME := NULL; RETURN;
    END IF;

    SELECT COUNT(*) INTO V_PW_MATCH
    FROM EMP_INFO WHERE EMP_CD = E_EMP_CD AND PWD = E_EMP_PWD;

    IF V_PW_MATCH = 0 THEN
        E_EMP_RESULT := 'WRONG_PASSWORD'; E_EMP_NAME := NULL; RETURN;
    END IF;

    SELECT E.EMP_NAME INTO E_EMP_NAME
    FROM EMP E JOIN EMP_INFO I ON E.EMP_CD = I.EMP_CD
    WHERE E.EMP_CD = E_EMP_CD;

    E_EMP_RESULT := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN E_EMP_RESULT := 'ERROR'; E_EMP_NAME := NULL;
END EMP_LOGIN;
/

-- 2. 사원 등록
CREATE OR REPLACE PROCEDURE EMP_CREATE (
     E_EMP_EMP_CD      IN EMP.EMP_CD%TYPE
    ,E_EMP_DEPT_CD     IN EMP.DEPT_CD%TYPE
    ,E_EMP_POSITION_CD IN EMP.POSITION_CD%TYPE
    ,E_EMP_EMP_NAME    IN EMP.EMP_NAME%TYPE
)
IS
    V_DEPT_CD     NUMBER;
    V_POSITION_CD NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_DEPT_CD FROM DEPT WHERE DEPT_CD = E_EMP_DEPT_CD;
    IF V_DEPT_CD = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, '존재하지 않는 부서입니다.');
    END IF;

    SELECT COUNT(*) INTO V_POSITION_CD FROM EMP_POSITION WHERE POSITION_CD = E_EMP_POSITION_CD;
    IF V_POSITION_CD = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, '존재하지 않는 직급입니다.');
    END IF;

    INSERT INTO EMP(EMP_CD, DEPT_CD, POSITION_CD, EMP_NAME, REG_DT)
    VALUES ('SW' || LPAD(EMP_SEQ.NEXTVAL, 4, '0'), E_EMP_DEPT_CD, E_EMP_POSITION_CD, E_EMP_EMP_NAME, SYSDATE);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END EMP_CREATE;
/

-- 3. 사원 정보 등록 (HIRE_DATE 파라미터 추가 - 2026-05-16 수정)
--    Java(EmpDAO)에서 6번째 파라미터로 입사일 전달, null이면 SYSDATE 사용
CREATE OR REPLACE PROCEDURE EMP_INFO_CREATE (
     E_EMP_CD    IN EMP_INFO.EMP_CD%TYPE
    ,E_PWD       IN EMP_INFO.PWD%TYPE
    ,E_TEL       IN EMP_INFO.TEL%TYPE
    ,E_EMAIL     IN EMP_INFO.EMAIL%TYPE
    ,E_ADDR      IN EMP_INFO.ADDR%TYPE
    ,E_HIRE_DATE IN DATE
)
IS
BEGIN
    INSERT INTO EMP_INFO(EMP_CD, PWD, TEL, EMAIL, ADDR, HIRE_DATE)
    VALUES (E_EMP_CD, E_PWD, E_TEL, E_EMAIL, E_ADDR,
            NVL(E_HIRE_DATE, SYSDATE));
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END EMP_INFO_CREATE;
/

-- 4. 사원 기본 수정
CREATE OR REPLACE PROCEDURE EMP_UPDATE (
     E_EMP_CD      IN EMP.EMP_CD%TYPE
    ,E_DEPT_CD     IN EMP.DEPT_CD%TYPE
    ,E_POSITION_CD IN EMP.POSITION_CD%TYPE
    ,E_EMP_NAME    IN EMP.EMP_NAME%TYPE
)
IS
BEGIN
    UPDATE EMP SET DEPT_CD=E_DEPT_CD, POSITION_CD=E_POSITION_CD, EMP_NAME=E_EMP_NAME
    WHERE EMP_CD = E_EMP_CD;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END EMP_UPDATE;
/

-- 5. 사원 정보 수정 (본인 + HR 공용)
CREATE OR REPLACE PROCEDURE EMP_INFO_UPDATE (
     E_EMP_CD   IN EMP_INFO.EMP_CD%TYPE
    ,E_EMP_NAME IN EMP.EMP_NAME%TYPE
    ,E_TEL      IN EMP_INFO.TEL%TYPE
    ,E_EMAIL    IN EMP_INFO.EMAIL%TYPE
    ,E_ADDR     IN EMP_INFO.ADDR%TYPE
    ,E_PWD      IN EMP_INFO.PWD%TYPE
)
IS
BEGIN
    UPDATE EMP SET EMP_NAME = E_EMP_NAME WHERE EMP_CD = E_EMP_CD;
    UPDATE EMP_INFO SET PWD=E_PWD, TEL=E_TEL, EMAIL=E_EMAIL, ADDR=E_ADDR
    WHERE EMP_CD = E_EMP_CD;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END EMP_INFO_UPDATE;
/

-- 6. 퇴사 처리 (EMP 유지, EMP_INFO → EXIT_EMP_INFO 이동)
--    VIEW_EMPLOYEE는 EMP_INFO INNER JOIN이므로 EMP_INFO 삭제 시 자동 제외
CREATE OR REPLACE PROCEDURE EMP_EXIT (
    E_EMP_CD IN EMP.EMP_CD%TYPE
)
IS
BEGIN
    -- 퇴사자 정보 보관
    INSERT INTO EXIT_EMP_INFO(EXIT_NO, EMP_CD, TEL, HIRE_DATE, EMAIL, ADDR, EXIT_DATE)
    SELECT EXIT_EMP_INFO_SEQ.NEXTVAL, EMP_CD, TEL, HIRE_DATE, EMAIL, ADDR, SYSDATE
    FROM EMP_INFO WHERE EMP_CD = E_EMP_CD;

    -- 해당 직원의 게시판 댓글 삭제
    DELETE FROM BOARD_COMMENT WHERE EMP_CD = E_EMP_CD;

    -- EMP_INFO 삭제 (EMP 레코드는 보존 → existsInEmpTable()이 이를 활용)
    DELETE FROM EMP_INFO WHERE EMP_CD = E_EMP_CD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END EMP_EXIT;
/

-- ── 출퇴근 ──────────────────────────────────────────────────

-- 7. 출근 (당일 중복 출근 방지 - 2026-05-16 수정)
CREATE OR REPLACE PROCEDURE ATTEND_IN (
    E_EMP_CD IN ATTEND_LOG.EMP_CD%TYPE
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM ATTEND_LOG
    WHERE TRIM(EMP_CD) = TRIM(E_EMP_CD)
      AND TYPE_CD = '001'
      AND TRUNC(REG_DT) = TRUNC(SYSDATE);

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, '이미 오늘 출근 처리되었습니다.');
    END IF;

    INSERT INTO ATTEND_LOG(LOG_NO, TYPE_CD, EMP_CD, REG_DT)
    VALUES (ATTEND_LOG_SEQ.NEXTVAL, '001', E_EMP_CD, SYSDATE);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END ATTEND_IN;
/

-- 8. 퇴근 (출근 없는 퇴근 방지 + 중복 퇴근 방지 - 2026-05-16 수정)
CREATE OR REPLACE PROCEDURE ATTEND_OUT (
    E_EMP_CD IN ATTEND_LOG.EMP_CD%TYPE
)
IS
    V_IN_COUNT  NUMBER;
    V_OUT_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_IN_COUNT FROM ATTEND_LOG
    WHERE TRIM(EMP_CD) = TRIM(E_EMP_CD)
      AND TYPE_CD = '001'
      AND TRUNC(REG_DT) = TRUNC(SYSDATE);

    IF V_IN_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, '오늘 출근 기록이 없어 퇴근 처리할 수 없습니다.');
    END IF;

    SELECT COUNT(*) INTO V_OUT_COUNT FROM ATTEND_LOG
    WHERE TRIM(EMP_CD) = TRIM(E_EMP_CD)
      AND TYPE_CD = '002'
      AND TRUNC(REG_DT) = TRUNC(SYSDATE);

    IF V_OUT_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, '이미 오늘 퇴근 처리되었습니다.');
    END IF;

    INSERT INTO ATTEND_LOG(LOG_NO, TYPE_CD, EMP_CD, REG_DT)
    VALUES (ATTEND_LOG_SEQ.NEXTVAL, '002', E_EMP_CD, SYSDATE);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END ATTEND_OUT;
/

-- ── 부서 ────────────────────────────────────────────────────

-- 9. 부서 등록/수정/삭제 통합 프로시저
CREATE OR REPLACE PROCEDURE DEPT_HISTORY_CUD (
     E_TYPE      IN VARCHAR2
    ,E_DEPT_CD   IN DEPT.DEPT_CD%TYPE
    ,E_DEPT_NAME IN DEPT.DEPT_NAME%TYPE
)
IS
    V_DEPT_CD    DEPT.DEPT_CD%TYPE;
    V_NAME_COUNT NUMBER;
BEGIN
    IF E_TYPE = 'INSERT' THEN
        SELECT COUNT(*) INTO V_NAME_COUNT FROM DEPT WHERE DEPT_NAME = E_DEPT_NAME;
        IF V_NAME_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 부서명입니다.');
        END IF;
        V_DEPT_CD := 'DE' || LPAD(DEPT_SEQ.NEXTVAL, 2, '0');
        INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES(V_DEPT_CD, E_DEPT_NAME);
        INSERT INTO DEPT_HISTORY(HISTORY_CD, DEPT_CD, DEPT_NAME)
        VALUES ('DH' || LPAD(DEPT_HISTORY_SEQ.NEXTVAL, 2, '0'), V_DEPT_CD, E_DEPT_NAME);

    ELSIF E_TYPE = 'UPDATE' THEN
        SELECT COUNT(*) INTO V_NAME_COUNT
        FROM DEPT WHERE DEPT_NAME = E_DEPT_NAME AND DEPT_CD != E_DEPT_CD;
        IF V_NAME_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20001, '이미 존재하는 부서명입니다.');
        END IF;
        UPDATE DEPT SET DEPT_NAME = E_DEPT_NAME WHERE DEPT_CD = E_DEPT_CD;
        INSERT INTO DEPT_HISTORY(HISTORY_CD, DEPT_CD, DEPT_NAME)
        VALUES ('DH' || LPAD(DEPT_HISTORY_SEQ.NEXTVAL, 2, '0'), E_DEPT_CD, E_DEPT_NAME);

    ELSIF E_TYPE = 'DELETE' THEN
        INSERT INTO DEPT_HISTORY(HISTORY_CD, DEPT_CD, DEPT_NAME)
        SELECT 'DH' || LPAD(DEPT_HISTORY_SEQ.NEXTVAL, 2, '0'), DEPT_CD, DEPT_NAME
        FROM DEPT WHERE DEPT_CD = E_DEPT_CD;
        DELETE FROM DEPT WHERE DEPT_CD = E_DEPT_CD;
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END DEPT_HISTORY_CUD;
/

-- ── 직급 ────────────────────────────────────────────────────

-- 10. 직급 등록/수정/삭제 통합 프로시저
CREATE OR REPLACE PROCEDURE POSITION_HISTORY_CUD (
     E_TYPE          IN VARCHAR2
    ,E_POSITION_CD   IN EMP_POSITION.POSITION_CD%TYPE
    ,E_POSITION_NAME IN EMP_POSITION.POSITION_NAME%TYPE
    ,E_GRADE         IN EMP_POSITION.GRADE%TYPE
)
IS
    V_POSITION_CD EMP_POSITION.POSITION_CD%TYPE;
    V_NAME_COUNT  NUMBER;
BEGIN
    IF E_TYPE = 'INSERT' THEN
        SELECT COUNT(*) INTO V_NAME_COUNT FROM EMP_POSITION WHERE POSITION_NAME = E_POSITION_NAME;
        IF V_NAME_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 직급명입니다.');
        END IF;
        V_POSITION_CD := 'PO' || LPAD(EMP_POSITION_SEQ.NEXTVAL, 2, '0');
        INSERT INTO EMP_POSITION(POSITION_CD, POSITION_NAME, GRADE)
        VALUES (V_POSITION_CD, E_POSITION_NAME, E_GRADE);
        INSERT INTO POSITION_HISTORY(HISTORY_CD, POSITION_CD, POSITION_NAME, GRADE)
        VALUES ('PH' || LPAD(POSITION_HISTORY_SEQ.NEXTVAL, 2, '0'), V_POSITION_CD, E_POSITION_NAME, E_GRADE);

    ELSIF E_TYPE = 'UPDATE' THEN
        SELECT COUNT(*) INTO V_NAME_COUNT
        FROM EMP_POSITION WHERE POSITION_NAME = E_POSITION_NAME AND POSITION_CD != E_POSITION_CD;
        IF V_NAME_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20002, '이미 존재하는 직급명입니다.');
        END IF;
        UPDATE EMP_POSITION SET POSITION_NAME=E_POSITION_NAME, GRADE=E_GRADE
        WHERE POSITION_CD = E_POSITION_CD;
        INSERT INTO POSITION_HISTORY(HISTORY_CD, POSITION_CD, POSITION_NAME, GRADE)
        VALUES ('PH' || LPAD(POSITION_HISTORY_SEQ.NEXTVAL, 2, '0'), E_POSITION_CD, E_POSITION_NAME, E_GRADE);

    ELSIF E_TYPE = 'DELETE' THEN
        INSERT INTO POSITION_HISTORY(HISTORY_CD, POSITION_CD, POSITION_NAME, GRADE)
        SELECT 'PH' || LPAD(POSITION_HISTORY_SEQ.NEXTVAL, 2, '0'), POSITION_CD, POSITION_NAME, GRADE
        FROM EMP_POSITION WHERE POSITION_CD = E_POSITION_CD;
        DELETE FROM EMP_POSITION WHERE POSITION_CD = E_POSITION_CD;
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END POSITION_HISTORY_CUD;
/

-- ── 파일 ────────────────────────────────────────────────────

-- 11. 파일 등록 (게시판·결재 문서 공용), 등록된 FILE_NO 반환
CREATE OR REPLACE PROCEDURE PRC_FILE_INSERT (
     P_EMP_CD      IN  SH_FILE.EMP_CD%TYPE
    ,P_ORIGIN_NAME IN  SH_FILE.ORIGIN_NAME%TYPE
    ,P_SAVED_NAME  IN  SH_FILE.SAVED_NAME%TYPE
    ,P_PATH        IN  SH_FILE.PATH%TYPE
    ,P_FILE_NO     OUT NUMBER
)
IS
    V_FILE_NO NUMBER;
BEGIN
    SELECT SH_FILE_SEQ.NEXTVAL INTO V_FILE_NO FROM DUAL;

    INSERT INTO SH_FILE(FILE_NO, EMP_CD, ORIGIN_NAME, SAVED_NAME, PATH)
    VALUES (V_FILE_NO, P_EMP_CD, P_ORIGIN_NAME, P_SAVED_NAME, P_PATH);

    P_FILE_NO := V_FILE_NO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN P_FILE_NO := -1; ROLLBACK; RAISE;
END PRC_FILE_INSERT;
/

-- ── 결재 ────────────────────────────────────────────────────

-- 12. 결재 문서 등록 (결재 라인 포함)
CREATE OR REPLACE PROCEDURE PRC_APRV_DOC_INSERT (
     P_PARENT_CD   IN  SH_DOCUMENT.PARENT_DOC_CD%TYPE
    ,P_DOC_TYPE_CD IN  SH_DOCUMENT.TYPE_CD%TYPE
    ,P_WORK_CD     IN  SH_DOCUMENT.WORK_CD%TYPE
    ,P_EMP_CD      IN  SH_DOCUMENT.EMP_CD%TYPE
    ,P_TITLE       IN  SH_DOCUMENT.TITLE%TYPE
    ,P_CONTENT     IN  SH_DOCUMENT.CONTENTS%TYPE
    ,P_DOC_CD      OUT VARCHAR2
)
IS
    V_DOC_CD VARCHAR2(10);
    V_FLOW   NUMBER := 0;
BEGIN
    SELECT 'DC' || LPAD(DOC_SEQ.NEXTVAL, 4, '0') INTO V_DOC_CD FROM DUAL;

    INSERT INTO SH_DOCUMENT(DOC_CD, PARENT_DOC_CD, TYPE_CD, WORK_CD, EMP_CD, TITLE, CONTENTS, REG_DT)
    VALUES (V_DOC_CD, P_PARENT_CD, P_DOC_TYPE_CD, P_WORK_CD, P_EMP_CD, P_TITLE, P_CONTENT, SYSDATE);

    -- 해당 업무 흐름(WORK_DEPT_RULE)에서 결재 라인 자동 생성
    FOR R IN (
        SELECT E.EMP_CD, WDR.FLOW
        FROM WORK_DEPT_RULE WDR
        JOIN EMP E ON E.DEPT_CD = WDR.DEPT_CD
        JOIN EMP_INFO I ON E.EMP_CD = I.EMP_CD
        WHERE WDR.WORK_CD = P_WORK_CD
        ORDER BY WDR.FLOW
    ) LOOP
        INSERT INTO APRV_LINE(DOC_CD, EMP_CD, FLOW)
        VALUES (V_DOC_CD, R.EMP_CD, R.FLOW);
    END LOOP;

    P_DOC_CD := V_DOC_CD;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN P_DOC_CD := ''; ROLLBACK; RAISE;
END PRC_APRV_DOC_INSERT;
/

-- 13. 업무 지시 문서 등록
CREATE OR REPLACE PROCEDURE PRC_DOC_INSERT (
     P_PARENT_CD   IN  SH_DOCUMENT.PARENT_DOC_CD%TYPE
    ,P_DOC_TYPE_CD IN  SH_DOCUMENT.TYPE_CD%TYPE
    ,P_WORK_CD     IN  SH_DOCUMENT.WORK_CD%TYPE
    ,P_EMP_CD      IN  SH_DOCUMENT.EMP_CD%TYPE
    ,P_TITLE       IN  SH_DOCUMENT.TITLE%TYPE
    ,P_CONTENT     IN  SH_DOCUMENT.CONTENTS%TYPE
    ,P_DOC_CD      OUT VARCHAR2
)
IS
    V_DOC_CD VARCHAR2(10);
BEGIN
    SELECT 'DC' || LPAD(DOC_SEQ.NEXTVAL, 4, '0') INTO V_DOC_CD FROM DUAL;

    INSERT INTO SH_DOCUMENT(DOC_CD, PARENT_DOC_CD, TYPE_CD, WORK_CD, EMP_CD, TITLE, CONTENTS, REG_DT)
    VALUES (V_DOC_CD, P_PARENT_CD, P_DOC_TYPE_CD, P_WORK_CD, P_EMP_CD, P_TITLE, P_CONTENT, SYSDATE);

    P_DOC_CD := V_DOC_CD;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN P_DOC_CD := ''; ROLLBACK; RAISE;
END PRC_DOC_INSERT;
/

-- 14. 결재 이력 등록
CREATE OR REPLACE PROCEDURE PRC_APRV_LOG_INSERT (
     P_DOC_CD   IN APRV_LOG.DOC_CD%TYPE
    ,P_TYPE_CD  IN APRV_LOG.TYPE_CD%TYPE
    ,P_EMP_CD   IN APRV_LOG.EMP_CD%TYPE
    ,P_COMMENTS IN APRV_LOG.COMMENTS%TYPE
)
IS
BEGIN
    INSERT INTO APRV_LOG(LOG_NO, DOC_CD, EMP_CD, TYPE_CD, COMMENTS, REG_DT)
    VALUES (MANAGER_SEQ.NEXTVAL, P_DOC_CD, P_EMP_CD, P_TYPE_CD, P_COMMENTS, SYSDATE);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END PRC_APRV_LOG_INSERT;
/

-- 15. 업무 담당자 등록
CREATE OR REPLACE PROCEDURE PRC_MANAGER_INSERT (
     P_WORK_CD        IN MANAGER.WORK_CD%TYPE
    ,P_MANAGER_EMP_CD IN MANAGER.MANAGER_EMP_CD%TYPE
    ,P_REG_EMP_CD     IN MANAGER.REG_EMP_CD%TYPE
    ,P_ISSUE_TYPE     IN MANAGER.ISSUE_TYPE%TYPE
    ,P_ISSUE_DATE     IN VARCHAR2   -- 'YYYY-MM-DD' 형식
)
IS
BEGIN
    INSERT INTO MANAGER(MANAGER_NO, WORK_CD, MANAGER_EMP_CD, REG_EMP_CD, ISSUE_TYPE, ISSUE_DATE)
    VALUES (MANAGER_SEQ.NEXTVAL, P_WORK_CD, P_MANAGER_EMP_CD, P_REG_EMP_CD,
            P_ISSUE_TYPE, TO_DATE(P_ISSUE_DATE, 'YYYY-MM-DD'));
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END PRC_MANAGER_INSERT;
/


-- ============================================================
-- 7. 기초 데이터 (Initial Data)
-- ============================================================

-- 출퇴근 유형
INSERT INTO ATTEND_TYPE VALUES('001', '출근');
INSERT INTO ATTEND_TYPE VALUES('002', '퇴근');

-- 부서 (DE01~DE05)
INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES('DE01', '개발부');
INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES('DE02', '인사부');
INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES('DE03', '디자인부');
INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES('DE04', '경영부');
INSERT INTO DEPT(DEPT_CD, DEPT_NAME) VALUES('DE05', '행정부');

-- 부서 이력 초기값
INSERT INTO DEPT_HISTORY VALUES('DH01','DE01','개발부',  TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO DEPT_HISTORY VALUES('DH02','DE02','인사부',  TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO DEPT_HISTORY VALUES('DH03','DE03','디자인부',TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO DEPT_HISTORY VALUES('DH04','DE04','경영부',  TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO DEPT_HISTORY VALUES('DH05','DE05','행정부',  TO_DATE('2026-04-01','YYYY-MM-DD'));

-- 직급 (PO01~PO05, GRADE: 10~50)
INSERT INTO EMP_POSITION VALUES('PO01','사원',10);
INSERT INTO EMP_POSITION VALUES('PO02','대리',20);
INSERT INTO EMP_POSITION VALUES('PO03','과장',30);
INSERT INTO EMP_POSITION VALUES('PO04','차장',40);
INSERT INTO EMP_POSITION VALUES('PO05','부장',50);

-- 직급 이력 초기값
INSERT INTO POSITION_HISTORY VALUES('PH01','PO01','사원',10,TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO POSITION_HISTORY VALUES('PH02','PO02','대리',20,TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO POSITION_HISTORY VALUES('PH03','PO03','과장',30,TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO POSITION_HISTORY VALUES('PH04','PO04','차장',40,TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO POSITION_HISTORY VALUES('PH05','PO05','부장',50,TO_DATE('2026-04-01','YYYY-MM-DD'));

-- 결재 종류 (001=승인, 002=반려, 003=전결)
INSERT INTO APRV_TYPE VALUES('001','승인');
INSERT INTO APRV_TYPE VALUES('002','반려');
INSERT INTO APRV_TYPE VALUES('003','전결');

-- 문서 종류 (예시 - 실제 프로젝트 규칙에 맞게 수정)
INSERT INTO DOC_TYPE VALUES('001','업무 보고');
INSERT INTO DOC_TYPE VALUES('002','업무 지시');

-- 게시판 종류 (예시)
INSERT INTO BOARD_TYPE VALUES('001','공지사항');
INSERT INTO BOARD_TYPE VALUES('002','자유게시판');

-- 업무 종류 (예시)
INSERT INTO WORK_TYPE VALUES('001','기획');
INSERT INTO WORK_TYPE VALUES('002','개발');
INSERT INTO WORK_TYPE VALUES('003','운영');

COMMIT;


-- ============================================================
-- 8. 변경 이력 요약 (vs. 기존 sh_company.sql)
-- ============================================================
-- [추가] 전체 테이블 CREATE DDL (EMP, EMP_INFO, ATTEND_LOG 등)
-- [추가] 전체 시퀀스 생성 구문
-- [추가] 전체 뷰 (VIEW_WORK_SEARCH, VIEW_MANAGER, VIEW_APRV_* 등)
-- [추가] FN_GET_EMP_NAME, FN_GET_APRV_CURRENT_FLOW 함수
-- [추가] PRC_FILE_INSERT, PRC_APRV_DOC_INSERT, PRC_DOC_INSERT 프로시저
-- [추가] PRC_APRV_LOG_INSERT, PRC_MANAGER_INSERT 프로시저
-- [수정] EMP_INFO_CREATE : HIRE_DATE 하드코딩(SYSDATE) → 파라미터(6번째) 추가
--         (Java EmpDAO.insertEmp()도 함께 수정 완료)
-- [수정] ATTEND_IN  : 당일 중복 출근 방지 로직 추가 (RAISE_APPLICATION_ERROR -20001)
-- [수정] ATTEND_OUT : 출근 없는 퇴근 방지(-20002) + 중복 퇴근 방지(-20003)
-- [수정] EMP_EXIT   : 두 버전 중 최종본 채택 (EMP 유지, EMP_INFO만 삭제)
-- [정리] 기존 파일의 임시 SELECT/ALTER/DROP 구문 제거
-- ============================================================
